### ISSUE TITLE
Error occurred while parsing your function triggers.

### ISSUE THREAD

**Issue by bigdigitalSVN** [dexterlabora/MerakiLocationFirebase#3]
When I go to deploy, I use admin privileges and then I get this error, it succeeds until functions.

```
sudo firebase deploy

=== Deploying to 'db-name'...

i  deploying database, functions, hosting
i  database: checking rules syntax...
✔  database: rules syntax for database db-name is valid
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'databaseURL' of undefined
    at RepoManager.databaseFromApp (/home/bitnami/MerakiLocationFirebase/functions/node_modules/@firebase/database/dist/index.node.cjs.js:14985:39)
    at Object.instance.INTERNAL.registerService.Reference [as database] (/home/bitnami/MerakiLocationFirebase/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15526:130)
    at FirebaseAppImpl._getService (/home/bitnami/MerakiLocationFirebase/functions/node_modules/@firebase/app/dist/index.cjs.js:134:66)
    at FirebaseAppImpl.(anonymous function) [as database] (/home/bitnami/MerakiLocationFirebase/functions/node_modules/@firebase/app/dist/index.cjs.js:323:31)
    at Object.serviceNamespace [as database] (/home/bitnami/MerakiLocationFirebase/functions/node_modules/@firebase/app/dist/index.cjs.js:308:32)
    at Object.<anonymous> (/home/bitnami/MerakiLocationFirebase/functions/index.js:13:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
Edit index.js file:

Comment out:
// const appConfig = functions.config().firebase;
// firebase.initializeApp(appConfig);

Add:
// Initialize Firebase
firebase.initializeApp(JSON.parse(process.env.FIREBASE_CONFIG));
